### ISSUE TITLE
Camera2 | NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue() 

### ISSUE THREAD

**Issue by kishorejethava** [DFTinc/onyx-5.0-demo#6]
Test case
Initially `start onyx` button is disabled
button enabled on press of  `Refresh config`
press on `start onyx` and it crashed with following logcat

Tested in Devices:  
**Motorola C Plus with v7.0**
**Motorola Moto G3 v6.0.1**

Note : I have dev licence key
I guess issue is related to **Camera2** API

```
2020-09-07 17:34:04.653 24613-24613/com.dft.onyx50demo E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
2020-09-07 17:34:18.995 24613-24613/com.dft.onyx50demo E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
2020-09-07 17:34:19.604 24613-24680/com.dft.onyx50demo E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
2020-09-07 17:34:19.748 24613-24659/com.dft.onyx50demo E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
    Process: com.dft.onyx50demo, PID: 24613
    java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
        at com.dft.onyxcamera.ui.j.b.b(SourceFile:4)
        at com.dft.onyxcamera.ui.j.b.a(SourceFile:13)
        at com.dft.onyxcamera.ui.g.a(SourceFile:144)
        at com.dft.onyxcamera.ui.g.b(SourceFile:2)
        at com.dft.onyxcamera.ui.g$f.onConfigured(SourceFile:10)
        at java.lang.reflect.Method.invoke(Native Method)
        at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
        at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by cdwheatley** [comment]
Hi @kishorejethava, I had an error in the version 6.11.1 of onyx-camera.  Please try the latest version 6.11.5 which should clear the issue up.
